### ISSUE TITLE
Getting ERR_REQUIRE_ESM error on vitepress-plugin-tabs

### ISSUE THREAD

**Issue by ranaroussi** [sapphi-red/vitepress-plugins#17]
```sh
$ vitepress dev docs
vitepress v1.0.0-alpha.32
failed to load config from /Users/ran/vitepress/docs/.vitepress/config.js
failed to start server. error:
 Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/ran/vitepress/node_modules/vitepress-plugin-tabs/dist/index.js from /Users/ran/vitepress/docs/.vitepress/config.js not supported.
Instead change the require of index.js in /Users/ran/vitepress/docs/.vitepress/config.js to a dynamic import() which is available in all CommonJS modules.
    at _require.extensions.<computed> [as .js] (file:///Users/ran/vitepress/node_modules/vite/dist/node/chunks/dep-6305614c.js:63133:17)
    at Object.<anonymous> (/Users/ran/vitepress/docs/.vitepress/config.js:25:36)
    at _require.extensions.<computed> [as .js] (file:///Users/ran/vitepress/node_modules/vite/dist/node/chunks/dep-6305614c.js:63130:24)
    at loadConfigFromBundledFile (file:///Users/ran/vitepress/node_modules/vite/dist/node/chunks/dep-6305614c.js:63138:21)
    at loadConfigFromFile (file:///Users/ran/vitepress/node_modules/vite/dist/node/chunks/dep-6305614c.js:62996:34)
    at async resolveUserConfig (file:///Users/ran/vitepress/node_modules/vitepress/dist/node/serve-a3abc752.js:10510:27)
    at async resolveConfig (file:///Users/ran/vitepress/node_modules/vitepress/dist/node/serve-a3abc752.js:10460:48)
    at async createServer (file:///Users/ran/vitepress/node_modules/vitepress/dist/node/serve-a3abc752.js:35767:18)
    at async createDevServer (file:///Users/ran/vitepress/node_modules/vitepress/dist/node/cli.js:286:20) {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.
```

Any ideas on how to solve it?

Thanks!

**Comment by sapphi-red** [comment]
These plugins only support ESM.
I guess it'll work if you renamed `.vitepress/config.js` to `.vitepress/config.mjs`.

**Comment by sapphi-red** [comment]
Closing due to lack of response.
